/*Task 1*/
console.log("Task 1");
let a = 'hello';
console.log(a);
alert(a);
document.write(a);
document.write('<br>');
let b = 'owu';
console.log(b);
alert(b);
document.write(b);
document.write('<br>');
let c = 'com';
console.log(c);
alert(c);
document.write(c);
document.write('<br>');
let   d = 'ua';
console.log(d);
alert(d);
document.write(d);
document.write('<br>');
let e = 1;
console.log(e);
alert(e);
document.write(e);
document.write('<br>');
let f = 10;
console.log(f);
alert(f);
document.write(f);
document.write('<br>');
let g = -999;
console.log(g);
alert(g);
document.write(g);
document.write('<br>');
let h = 123;
console.log(h);
alert(h);
document.write(h);
document.write('<br>');
let i = 3.14;
console.log(i);
alert(i);
document.write(i);
document.write('<br>');
let j = 2.7;
console.log(j);
alert(j);
document.write(j);
document.write('<br>');
let k = 16;
console.log(k);
alert(k);
document.write(k);
document.write('<br>');
let l = true;
console.log(l);
alert(l);
document.write(l);
document.write('<br>');
let m = false;
console.log(m);
alert(m);
document.write(m);
document.write('<br>');

/*Task 2*/
console.log(" ");
console.log("Task 2");
let firstName = "Ігор";
let middleName = "Михайлович";
let lastName = "Красільчук";
let person;
person= firstName+" "+middleName+" "+lastName;
console.log(person);

/*Task 3*/
console.log(" ");
console.log("Task 3");
let x = 100;
let y = '100';
let z = true;
console.log(typeof (x));
console.log(typeof (y));
console.log(typeof (z));

/*Task 4*/
console.log(" ");
console.log("Task 4");
let fname = prompt('Введіть своє імя');
console.log(fname);
let mname = prompt('Як до Вас  звертатись по батькові?');
console.log(mname);
let age = prompt('Скільки Вам років?');
console.log(age);
